### ISSUE TITLE
Fix flaky test with code examples list

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/frontend#1478]
<img width="834" alt="Screenshot 2024-03-21 at 17 38 49" src="https://github.com/codecrafters-io/frontend/assets/3893573/0f62618e-cb8e-4512-9e10-9512a29cfc77">

Example run: https://github.com/codecrafters-io/frontend/pull/1476/checks?check_run_id=22935189969

**Comment by VasylMarchuk** [comment]
It fails for me on local host too, as well as 3-4 others (which count API requests). Would be great to fix!

**Comment by rohitpaulk** [comment]
We changed the way this page works so this test isn't needed anymore
