### ISSUE TITLE
Upgrade to ember 5.8

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/frontend#2032]

**Comment by VasylMarchuk** [comment]
Release notes: 

- https://blog.emberjs.com/ember-released-5-8
- https://blog.emberjs.com/ember-released-5-7
- https://blog.emberjs.com/ember-released-5-6

**Comment by VasylMarchuk** [comment]
Why not all the way to ember 5.10, which is currently latest? @rohitpaulk

**Comment by rohitpaulk** [comment]
@VasylMarchuk LTS releases usually have fewer compatibility issues, 5.8 is the latest LTS if I'm not wrong. The only time we moved off LTS in the past was because there was an embroider compatibility issue and we had to upgrade to be able to use embroider.

**Comment by VasylMarchuk** [comment]
Ah gotcha, 5.8 is latest LTS yep
